# Generated by Django 3.2.13 on 2022-05-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('dirige', models.CharField(max_length=50)),
                ('titulos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
                ('cantidad_de_jugadores', models.IntegerField()),
                ('torneo_liga_campeonato', models.CharField(max_length=50)),
                ('puesto', models.IntegerField()),
                ('partidos_jugados', models.IntegerField()),
                ('titulos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('posicion', models.CharField(max_length=50)),
                ('numero_de_camiseta', models.IntegerField()),
                ('club_equipo', models.CharField(max_length=50)),
            ],
        ),
    ]
