# Generated by Django 3.2.13 on 2022-06-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFutbol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='pie_habil',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
