# Generated by Django 3.2.13 on 2022-06-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFutbol', '0002_jugador_pie_habil'),
    ]

    operations = [
        migrations.AddField(
            model_name='directortecnico',
            name='dias_disponibles',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='dias_de_partido',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='goles_a_favor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='goles',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
