# Generated by Django 3.2.13 on 2022-06-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFutbol', '0006_auto_20220607_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
